{{- if .Values.rbac.createClusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sparkapplication.clusterRoleBindingName" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.sparkOperator.serviceAccount }}
    namespace: {{ .Values.rbac.sparkOperator.namespace }}
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountDriver }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.rbac.clusterRoleBinding.subjects }}
{{ toYaml .Values.rbac.clusterRoleBinding.subjects | indent 2 }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: {{ include "sparkapplication.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
