{{- if and (not .Values.existingConfigMaps) (.Values.configMaps.httpCredentials) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sparkapplication.fullname" . }}-http-credentials
data:
  http_credentials.json: |
{{- tpl .Values.configMaps.httpCredentials . | nindent 4 }}
{{- end }}
