{{- if and (not .Values.existingConfigMaps) (.Values.configMaps.batchJobLog4j2) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sparkapplication.fullname" . }}-batch-job-log4j2
data:
  batch_job_log4j2.xml: |
{{- tpl .Values.configMaps.batchJobLog4j2 . | nindent 4 }}
{{- end }}
