{{- if and (not .Values.existingConfigMaps) (.Values.configMaps.log4j2) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sparkapplication.fullname" . }}-log4j2
data:
  log4j2.xml: |
{{- tpl .Values.configMaps.log4j2 . | nindent 4 }}
{{- end }}
