{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "sparkapplication.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "sparkapplication.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.ingressRoute.rules }}
    - kind: "Rule"
      match: {{ .match | quote }}
      {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace }}
        {{- end }}
      {{- end}}
      priority: {{ .priority | default 0 }}
      services:
        {{- range .services }}
        - kind: Service
          name: {{ .name }}
          namespace: {{ .namespace }}
          port: {{ .port }}
        {{- end}}
    {{- end }}
  {{- if .Values.ingressRoute.tls }}
  tls:
    {{- toYaml .Values.ingressRoute.tls | nindent 4 }}
  {{- end }}
{{- end }}
