{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "sparkapplication.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "sparkapplication.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressRoute.tls }}
  tls:
    {{- range .Values.ingressRoute.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  entrypoints: |-
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . | title }}
    {{- end }}
  routes:
    {{- range .Values.ingressRoute.rules }}
    - kind: "Rule"
      match: {{ .match | quote }}
      services:
        {{- range .paths }}
        - name: {{ . }}
          port: {{ $svcPort }}
        {{- end}}
    {{- end }}
  {{- end }}
