{{- if .Values.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sparkapplicationlite.fullname" . }}
  labels:
    {{- include "sparkapplication.liteLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sparkapplication.liteSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.configMaps.backendConfig }}
        checksum/backend-config: {{ include (print $.Template.BasePath "/configmap_backend_config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.configMaps.batchJobLog4j2 }}
        checksum/batch-job-log4j2: {{ include (print $.Template.BasePath "/configmap_batch_job_log4j2.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.configMaps.customBatchConfig }}
        checksum/custom-batch-config: {{ include (print $.Template.BasePath "/configmap_custom_batch_config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.configMaps.httpCredentials }}
        checksum/http-credentials: {{ include (print $.Template.BasePath "/configmap_http_credentials.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.configMaps.layerCatalog }}
        checksum/layercatalog: {{ include (print $.Template.BasePath "/configmap_layercatalog.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.configMaps.log4j2 }}
        checksum/log4j2: {{ include (print $.Template.BasePath "/configmap_log4j2.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.configMaps.prometheusConfig }}
        checksum/prometheus-config: {{ include (print $.Template.BasePath "/configmap_prometheus_config.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "sparkapplication.liteLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ required "Please provide a rbac.serviceAccountDriver" .Values.rbac.serviceAccountDriver }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.driver.podSecurityContext | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ required "Please provide an image" .Values.image }}:{{ required "Please provide an image version" .Values.imageVersion }}
          command: ["/opt/openeo/bin/python3", "/opt/openeo/bin/openeo_kube_lite.py"]
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            {{- if .Values.driver.env }}
              {{- range $key, $value :=  .Values.driver.env }}
              - name: {{ $key }}
                value: {{ $value | quote }}
              {{- end }}
            {{- end }}
            {{- with .Values.driver.extraEnv }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.global.extraEnv }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if .Values.configMaps.backendConfig }}
              - name: OPENEO_BACKEND_CONFIG
                value: "/opt/backend_config/backendconfig.py"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.driver.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if not .Values.existingConfigMaps }}
          {{- if .Values.configMaps.backendConfig }}
            - mountPath: /opt/backend_config/backendconfig.py
              name: {{ include "sparkapplication.fullname" . }}-backend-config
              subPath: backendconfig.py
          {{- end }}
          {{- if .Values.configMaps.batchJobLog4j2 }}
            - mountPath: /opt/batch_job_log4j2.xml
              name: {{ include "sparkapplication.fullname" . }}-batch-job-log4j2
              subPath: batch_job_log4j2.xml
          {{- end }}
          {{- if .Values.configMaps.httpCredentials }}
            - mountPath: /opt/http_credentials/http_credentials.json
              name: {{ include "sparkapplication.fullname" . }}-http-credentials
              subPath: http_credentials.json
          {{- end }}
          {{- if .Values.configMaps.customBatchConfig }}
            - mountPath: /opt/venv/lib64/python{{ .Values.pythonVersion }}.{{ .Values.pythonMinorVersion }}/site-packages/openeogeotrellis/deploy/sparkapplication.yaml.j2
              name: {{ include "sparkapplication.fullname" . }}-custom-batch-config
              subPath: sparkapplication.yaml.j2
          {{- end }}
          {{- if .Values.configMaps.layerCatalog }}
            - mountPath: /opt/layercatalog.json
              name: {{ include "sparkapplication.fullname" . }}-layercatalog
              subPath: layercatalog.json
          {{- end }}
          {{- if .Values.configMaps.log4j2 }}
            - mountPath: /opt/log4j2.xml
              name: {{ include "sparkapplication.fullname" . }}-log4j2
              subPath: log4j2.xml
          {{- end }}
          {{- if .Values.configMaps.prometheusConfig }}
            - mountPath: /opt/prometheus_config.yaml
              name: {{ include "sparkapplication.fullname" . }}-prometheus-config
              subPath: prometheus_config.yaml
          {{- end }}
          {{- end }}


      {{- if or .Values.volumes (not .Values.existingConfigMaps) }}
      volumes:
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configMaps.backendConfig }}
        - configMap:
            name: {{ include "sparkapplication.fullname" . }}-backend-config
          name: {{ include "sparkapplication.fullname" . }}-backend-config
      {{- end }}
      {{- if .Values.configMaps.batchJobLog4j2 }}
        - configMap:
            name: {{ include "sparkapplication.fullname" . }}-batch-job-log4j2
          name: {{ include "sparkapplication.fullname" . }}-batch-job-log4j2
      {{- end }}
      {{- if .Values.configMaps.customBatchConfig }}
        - configMap:
            name: {{ include "sparkapplication.fullname" . }}-custom-batch-config
          name: {{ include "sparkapplication.fullname" . }}-custom-batch-config
      {{- end }}
      {{- if .Values.configMaps.httpCredentials }}
        - configMap:
            name: {{ include "sparkapplication.fullname" . }}-http-credentials
          name: {{ include "sparkapplication.fullname" . }}-http-credentials
      {{- end }}
      {{- if .Values.configMaps.layerCatalog }}
        - configMap:
            name: {{ include "sparkapplication.fullname" . }}-layercatalog
          name: {{ include "sparkapplication.fullname" . }}-layercatalog
      {{- end }}
      {{- if .Values.configMaps.log4j2 }}
        - configMap:
            name: {{ include "sparkapplication.fullname" . }}-log4j2
          name: {{ include "sparkapplication.fullname" . }}-log4j2
      {{- end }}
      {{- if .Values.configMaps.prometheusConfig }}
        - configMap:
            name: {{ include "sparkapplication.fullname" . }}-prometheus-config
          name: {{ include "sparkapplication.fullname" . }}-prometheus-config
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
