{{- if .Values.service.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sparkapplication.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sparkapplication.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name | trunc 63 }}-driver
{{- end }}
