---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name:  {{ .Release.Name | trunc 63 }}
  namespace: {{ .Release.Namespace }}
  labels:
    chartname: {{ .Chart.Name | trunc 63 | quote }}
    release: {{ .Release.Name | trunc 63 | quote }}
    revision: {{ .Release.Revision | quote }}
    sparkVersion: {{ .Values.sparkVersion | quote }}
    version: {{ .Chart.Version | quote }}
spec:
  type: "Python"
  pythonVersion: {{ .Values.pythonVersion | quote }}
  mode: "cluster"
  image: {{ required "Please provide an image" .Values.image }}:{{ required "Please provide an image version" .Values.imageVersion }}
  imagePullPolicy: {{ .Values.imagePullPolicy }}
  mainApplicationFile: {{ required "Please provide a main application file." .Values.mainApplicationFile | quote }}
  sparkVersion: {{ .Values.sparkVersion | quote }}
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  {{- if .Values.sparkConf }}
  sparkConf:
  {{- range $conf, $value := .Values.sparkConf }}
    {{ $conf | quote }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.volumes }}
  volumes:
{{ toYaml .Values.volumes | indent 3 }}
  {{- end }}
  {{- if or .Values.jarDependencies .Values.fileDependencies }}
  deps:
    {{- if .Values.jarDependencies }}
    jars:
    {{- range .Values.jarDependencies }}
      - {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.fileDependencies }}
    files:
    {{- range .Values.fileDependencies }}
      - {{ . | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
  driver:
    envVars:
      IMAGE_NAME: {{ .Values.image }}:{{ .Values.imageVersion }}
    {{- if .Values.driver.envVars }}
    {{- range $name, $value := .Values.driver.envVars }}
      {{ $name }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.driver.javaOptions }}
    javaOptions: {{ .Values.driver.javaOptions }}
    {{- end }}
    securityContext:
      privileged: {{ .Values.privileged }}
    cores: {{ .Values.driver.cores }}
    memory: {{ .Values.driver.memory }}
    hostNetwork: {{ .Values.hostNetwork | default false}}
    labels:
      app.kubernetes.io/name: {{ .Release.Name | trunc 63 }}-driver
      release: {{ .Release.Name | trunc 63 | quote }}
      revision: {{ .Release.Revision | quote }}
      sparkVersion: {{ .Values.sparkVersion | quote }}
      version: {{ .Chart.Version | quote }}
    serviceAccount: {{ required "Please provide a serviceaccount" .Values.serviceAccount }}
    {{- if .Values.volumeMounts }}
    volumeMounts:
{{ toYaml .Values.volumeMounts | indent 6 }}
    {{- end }}
  executor:
    {{- if .Values.executor.envVars }}
    envVars:
    {{- range $name, $value := .Values.executor.envVars }}
      {{ $name | quote }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.executor.javaOptions }}
    javaOptions: {{ .Values.executor.javaOptions }}
    {{- end }}
    securityContext:
      privileged: {{ .Values.privileged }}
    cores: {{ .Values.executor.cores }}
    instances: {{ .Values.executor.instances }}
    memory: {{ .Values.executor.memory }}
    hostNetwork: {{ .Values.hostNetwork | default false}}
    labels:
      release: {{ .Release.Name | trunc 63 | quote }}
      revision: {{ .Release.Revision | quote }}
      sparkVersion: {{ .Values.sparkVersion | quote }}
      version: {{ .Chart.Version | quote }}
    serviceAccount: {{ .Values.serviceAccount }}
    {{- if .Values.volumeMounts }}
    volumeMounts:
{{ toYaml .Values.volumeMounts | indent 6 }}
    {{- end }}
  {{- if .Values.jmxExporterJar }}
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: {{ .Values.jmxExporterJar }}
      port: {{ .Values.jmxPort | default 8090 }}
  {{- end }}
