{{- if .Values.spark_ui.ingress.enabled -}}
{{- $name := .Release.Name -}}
{{- $svcPort := .Values.spark_ui.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $name }}-driver-ui
  labels:
    {{- include "sparkapplication.labels" . | nindent 4 }}
  {{- with .Values.spark_ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.spark_ui.ingress.tls }}
  tls:
    {{- range .Values.spark_ui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.spark_ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              service:
                name: {{ $name }}-ui-svc
                port:
                  name: http
            pathType: 'Prefix'
          {{- end }}
    {{- end }}
  {{- end }}
