{{- if not .Values.ha.enabled -}}
---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name:  {{ .Release.Name | trunc 63 }}
  namespace: {{ .Release.Namespace }}
  labels:
    chartname: {{ .Chart.Name | trunc 63 | quote }}
    release: {{ .Release.Name | trunc 63 | quote }}
    revision: {{ .Release.Revision | quote }}
    sparkVersion: {{ .Values.sparkVersion | quote }}
    version: {{ .Chart.Version | quote }}
spec:
  type: "Python"
  pythonVersion: {{ .Values.pythonVersion | quote }}
  mode: "cluster"
  image: {{ required "Please provide an image" .Values.image }}:{{ required "Please provide an image version" .Values.imageVersion }}
  imagePullPolicy: {{ .Values.imagePullPolicy }}
  mainApplicationFile: {{ required "Please provide a main application file." .Values.mainApplicationFile | quote }}
  sparkVersion: {{ .Values.sparkVersion | quote }}
  restartPolicy:
    type: {{ .Values.restartPolicy.type }}
    onFailureRetries: {{ .Values.restartPolicy.onFailureRetries }}
    onFailureRetryInterval: {{ .Values.restartPolicy.onFailureRetryInterval }}
    onSubmissionFailureRetries: {{ .Values.restartPolicy.onSubmissionFailureRetries }}
    onSubmissionFailureRetryInterval: {{ .Values.restartPolicy.onSubmissionFailureRetryInterval }}
  {{- if .Values.sparkConf }}
  sparkConf:
  {{- range $conf, $value := .Values.sparkConf }}
    {{ $conf | quote }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  timeToLiveSeconds: {{ .Values.timeToLiveSeconds }}
  {{- if .Values.volumes }}
  volumes:
{{ toYaml .Values.volumes | indent 3 }}
  {{- end }}
  {{- if or .Values.jarDependencies .Values.fileDependencies }}
  deps:
    {{- if .Values.jarDependencies }}
    jars:
    {{- range .Values.jarDependencies }}
      - {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.fileDependencies }}
    files:
    {{- range .Values.fileDependencies }}
      - {{ . | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.dynamicAllocation }}
  dynamicAllocation:
    enabled: true
    initialExecutors: {{ .Values.dynamicAllocation.initialExecutors }}
    minExecutors: {{ .Values.dynamicAllocation.minExecutors }}
    maxExecutors: {{ .Values.dynamicAllocation.maxExecutors }}
  {{- end }}
  driver:
    {{- if .Values.driver.affinity }}
    affinity:
{{ toYaml .Values.driver.affinity | indent 6 }}
    {{- end }}
    env:
      - name: IMAGE_NAME
        value: {{ .Values.image }}:{{ .Values.imageVersion }}
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    {{- if .Values.driver.env }}
      {{- range $key, $value :=  .Values.driver.env }}
      - name: {{ $key }}
        value: {{ $value | quote }}
      {{- end }}
    {{- end }}
    {{- if .Values.driver.javaOptions }}
    javaOptions: {{ .Values.driver.javaOptions }}
    {{- end }}
    {{- if .Values.driver.podSecurityContext }}
    podSecurityContext:
{{ toYaml .Values.driver.podSecurityContext | indent 6 }}
    {{- end }}
    {{- if .Values.driver.ports }}
    ports:
{{ toYaml .Values.driver.ports | indent 6 }}
    {{- end }}
    securityContext:
      privileged: {{ .Values.privileged }}
    {{- if .Values.driver.cores }}
    cores: {{ .Values.driver.cores }}
    {{- end }}
    {{- if .Values.driver.coreRequest }}
    coreRequest: {{ .Values.driver.coreRequest }}
    {{- end }}
    coreLimit: {{ .Values.driver.coreLimit }}
    memory: {{ .Values.driver.memory }}
    memoryOverhead: {{ .Values.driver.memoryOverhead }}
    hostNetwork: {{ .Values.hostNetwork | default false}}
    labels:
      app.kubernetes.io/name: {{ .Release.Name | trunc 63 }}-driver
      release: {{ .Release.Name | trunc 63 | quote }}
      revision: {{ .Release.Revision | quote }}
      sparkVersion: {{ .Values.sparkVersion | quote }}
      version: {{ .Chart.Version | quote }}
    {{- if .Values.driver.labels }}
    {{- range $name, $value := .Values.driver.labels }}
      {{ $name }}: {{ $value }}
    {{- end }}
    {{- end}}
    serviceAccount: {{ required "Please provide a rbac.serviceAccountDriver" .Values.rbac.serviceAccountDriver }}
    {{- if .Values.volumeMounts }}
    volumeMounts:
{{ toYaml .Values.volumeMounts | indent 6 }}
{{- if .Values.driver.volumeMounts }}
{{ toYaml .Values.driver.volumeMounts | indent 6 }}
{{- end }}
    {{- end }}
    {{- if .Values.initContainers }}
    initContainers:
{{ toYaml .Values.initContainers | indent 6 }}
    {{- end }}
    {{- if .Values.driver.lifecycle}}
    lifecycle:
{{ toYaml .Values.driver.lifecycle | indent 6 }}
    {{- end }}
    terminationGracePeriodSeconds: {{ .Values.driver.terminationGracePeriodSeconds }}
  executor:
    {{- if .Values.executor.affinity }}
    affinity:
{{ toYaml .Values.executor.affinity | indent 6 }}
    {{- end }}
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    {{- if .Values.executor.env }}
      {{- range $key, $value :=  .Values.executor.env }}
      - name: {{ $key }}
        value: {{ $value | quote }}
      {{- end }}
    {{- end }}
    {{- if .Values.executor.javaOptions }}
    javaOptions: {{ .Values.executor.javaOptions }}
    {{- end }}
    {{- if .Values.executor.podSecurityContext }}
    podSecurityContext:
{{ toYaml .Values.executor.podSecurityContext | indent 6 }}
    {{- end }}
    securityContext:
      privileged: {{ .Values.privileged }}
    {{- if .Values.executor.cores }}
    cores: {{ .Values.executor.cores }}
    {{- end }}
    {{- if .Values.executor.coreRequest }}
    coreRequest: {{ .Values.executor.coreRequest }}
    {{- end }}
    coreLimit: {{ .Values.executor.coreLimit }}
    instances: {{ .Values.executor.instances }}
    memory: {{ .Values.executor.memory }}
    memoryOverhead: {{ .Values.executor.memoryOverhead }}
    hostNetwork: {{ .Values.hostNetwork | default false}}
    labels:
      release: {{ .Release.Name | trunc 63 | quote }}
      revision: {{ .Release.Revision | quote }}
      sparkVersion: {{ .Values.sparkVersion | quote }}
      version: {{ .Chart.Version | quote }}
    {{- if .Values.executor.labels }}
    {{- range $name, $value := .Values.executor.labels }}
      {{ $name }}: {{ $value }}
    {{- end }}
    {{- end}}
    serviceAccount: {{ .Values.rbac.serviceAccountExecutor }}
    {{- if .Values.volumeMounts }}
    volumeMounts:
{{ toYaml .Values.volumeMounts | indent 6 }}
{{- if .Values.executor.volumeMounts }}
{{ toYaml .Values.executor.volumeMounts | indent 6 }}
{{- end }}
    {{- end }}
    {{- if .Values.initContainers }}
    initContainers:
{{ toYaml .Values.initContainers | indent 6 }}
    {{- end }}
    {{- if .Values.executor.lifecycle}}
    lifecycle:
{{ toYaml .Values.executor.lifecycle | indent 6 }}
    {{- end }}
    terminationGracePeriodSeconds: {{ .Values.driver.terminationGracePeriodSeconds }}
  {{- if .Values.sparkUIOptions }}
  sparkUIOptions:
{{ toYaml .Values.sparkUIOptions | indent 4 }}
  {{- end }}
  {{- if .Values.priorityClassName }}
  batchSchedulerOptions:
    priorityClassName: {{ .Values.priorityClassName }}
  {{- end }}
  {{- if .Values.jmxExporterJar }}
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      {{- if .Values.monitoring.prometheus.configFile }}
      configFile: {{ .Values.monitoring.prometheus.configFile }}
      {{- end }}
      jmxExporterJar: {{ .Values.jmxExporterJar }}
      port: {{ .Values.jmxPort | default 8090 }}
  {{- end }}
{{- end }}
