{{- if and .Values.spark_ui.ingress.enabled .Values.ha.enabled -}}
{{ $namespace := .Release.Namespace }}
{{- range $index, $hosts := .Values.spark_ui.ingress.hosts }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ printf "%s-%s" (.host | trunc 55 ) "ingress" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    chartname: {{ $.Chart.Name | trunc 63 | quote }}
    release: {{ printf "%s-%d" ($.Release.Name | trunc 61 ) $index }}
    revision: {{ $.Release.Revision | quote }}
    sparkVersion: {{ $.Values.sparkVersion | quote }}
    version: {{ $.Chart.Version | quote }}
  {{- with $.Values.spark_ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $hosts.host | quote }}
      http:
        paths:
          {{- range $hosts.paths }}
          - path: {{ . }}
            backend:
              service:
                name: {{ printf "%s-%d-ui-svc" ($.Release.Name ) $index }}
                port:
                  name: http
            pathType: 'Prefix'
          {{- end }}
  {{- if $hosts.tls }}
  tls:
    - hosts:
        - {{ $hosts.host | quote }}
      secretName: {{ printf "%s-cert" ($hosts.host ) }}
    {{- end }}
  {{- end }}
{{- end }}
