apiVersion: v1
kind: Service
metadata:
  name: external-openeo-service
  namespace: spark-jobs
  annotations:
    loadbalancer.openstack.org/floating-network-id: '4a0a9ccb-69e0-4bbc-3456-b8d6ae9ef07c'
spec:
  type: LoadBalancer
  selector:
    name: openeo-driver
  ports:
    - port: 80
      targetPort: 50001
