{{- $hasSecretEnvVarValue := false }}
{{- with .Values.secretEnvVars.vars -}}
  {{- range $envVarName, $envVarSource := . -}}
    {{- if $envVarSource.value -}}
    {{- $hasSecretEnvVarValue = true -}}
    {{- end -}}
  {{- end}}
{{- end }}

{{- if $hasSecretEnvVarValue }}
  {{- with .Values.secretEnvVars -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
      {{- include "openeo-job-registry-api.labels" $ | nindent 4 }}
type: Opaque
data:
    {{- range $envVarName, $envVarSource := .vars }}
      {{- if $envVarSource.value }}
      {{ $envVarSource.keyInSecret }}: {{ $envVarSource.value | b64enc }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
