#!/usr/bin/env groovy

@Library('lib')_

containerImageBuildPipeline {
  dockerfile           = 'docker/Debian/Dockerfile'
  docker_registry_prod = 'vito-docker.artifactory.vgt.vito.be'
  image_name           = 'openeo-geotrellis'
  run_tests            = false
}
