#!/usr/bin/env groovy

@Library('lib')_

containerImageBuildPipeline {
  dockerfile           = 'docker/Debian/Dockerfile'
  docker_registry_prod = 'vito-docker.artifactory.vgt.vito.be'
  downstream_job       = 'bld.container_images/bld.openeo-geotrellis-kakadu'
  image_name           = 'openeo-geotrellis'
  promotion_job        = false
  run_tests            = false
}
