---
driver:
  cores: 2
  memory: "4096m"
executor:
  cores: 2
  instances: 1
  memory: "4096m"
imagePullPolicy: "IfNotPresent"
ingress:
  enabled: false
ingressRoute:
  enabled: false
jmxPort: 8090
pythonVersion: 3
service:
  enabled: false
  type: "ClusterIP"
sparkVersion: "2.4.5"
rbac:
  create: false
  createClusterRole: true
  createClusterRoleBinding: true
  serviceAccountDriver:
  serviceAccountExecutor: default
  sparkOperator:
    namespace: spark-operator
    serviceAccount: spark-operator
restartPolicy:
  type: "OnFailure"
  onFailureRetries: 3
  onFailureRetryInterval: 10
  onSubmissionFailureRetries: 5
  onSubmissionFailureRetryInterval: 20
spark_ui:
  port: 4040
  ingress:
    enabled: false
privileged: false
