---
driver:
  cores: 1
  coreLimit: "1200m"
  memory: "4096m"
  memoryOverhead: "2700m"
  terminationGracePeriodSeconds: 30
executor:
  cores: 1
  coreLimit: "1200m"
  instances: 1
  memory: "4096m"
  memoryOverhead: "2700m"
  terminationGracePeriodSeconds: 30
imagePullPolicy: "IfNotPresent"
ingress:
  enabled: false
ingressRoute:
  enabled: false
jmxPort: 8090
pythonVersion: 3
service:
  enabled: false
  type: "ClusterIP"
sparkVersion: "2.4.5"
rbac:
  create: false
  createClusterRole: true
  createClusterRoleBinding: true
  serviceAccountDriver:
  serviceAccountExecutor: default
  sparkOperator:
    namespace: spark-operator
    serviceAccount: spark-operator
restartPolicy:
  type: "OnFailure"
  onFailureRetries: 3
  onFailureRetryInterval: 10
  onSubmissionFailureRetries: 5
  onSubmissionFailureRetryInterval: 20
spark_ui:
  port: 4040
  ingress:
    enabled: false
privileged: false
timeToLiveSeconds: 172800
monitoring:
  podMonitor:
    enabled: false
