apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openeo-workspaces-api.fullname" . }}-secrets
  labels:
    {{- include "openeo-workspaces-api.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak_client_secret: {{ .Values.keycloak.external.clientSecret | b64enc | quote }}
  elasticsearch_password: {{ .Values.elasticsearch.external.password | b64enc | quote }}

