# This is a work in progress, to support Spark 3 in openEO-geotrellis

ARG GEOTRELLIS_EXTENSIONS_VERSION=2.3.0_2.12-SNAPSHOT
ARG GEOTRELLIS_BACKEND_ASSEMBLY_VERSION=0.4.6-openeo_2.12
ARG JMX_PROMETHEUS_JAVAAGENT_VERSION=0.13.0
ARG TINI_VERSION=v0.19.0
ARG OPENEO_ZIP

FROM vito-docker.artifactory.vgt.vito.be/almalinux8.5-spark-py-openeo:3.2.0

ARG TINI_VERSION
ARG GEOTRELLIS_EXTENSIONS_VERSION
ARG GEOTRELLIS_BACKEND_ASSEMBLY_VERSION
ARG JMX_PROMETHEUS_JAVAAGENT_VERSION
ARG OPENEO_ZIP

LABEL maintainer="VITO Remote Sensing"

USER root

COPY docker/CentOS/entrypoint.sh /opt/entrypoint.sh
COPY docker/creo_layercatalog.json /opt/layercatalog.json
COPY docker/log4j.properties /opt/log4j.properties

# Add S3 dependencies
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.2/hadoop-aws-3.2.2.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.199/aws-java-sdk-bundle-1.11.199.jar $SPARK_HOME/jars

# Download tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN printf "[global]\nindex = https://artifactory.vgt.vito.be/api/pypi/python-packages\nextra-index-url = https://artifactory.vgt.vito.be/api/pypi/python-packages/simple\n" > /etc/pip.conf && \
    chmod +x /usr/bin/tini && \
    chmod +x /opt/entrypoint.sh && \
    chown -R 18585:18585 $SPARK_HOME/jars && \
    yum install -y tensorflow-python38-2.3.0 && \
    python3.8 -m pip install -I --upgrade pip && \
    python3.8 -m pip install py4j boto3==1.16.25 kubernetes==12.0.1 PyYAML==5.3.1 Jinja2==2.11.2 spark_memlogger==0.6 && \
    rm -rf /root/.cache && \
    yum clean all && \
    rm -rf /var/cache/yum/*

WORKDIR /opt

RUN curl -O https://artifactory.vgt.vito.be/auxdata-public/openeo/geotrellis-backend-assembly-${GEOTRELLIS_BACKEND_ASSEMBLY_VERSION}.jar && \
     curl -O https://artifactory.vgt.vito.be/libs-snapshot-public/org/openeo/geotrellis-extensions/${GEOTRELLIS_EXTENSIONS_VERSION}/geotrellis-extensions-${GEOTRELLIS_EXTENSIONS_VERSION}.jar && \
    curl -O https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${JMX_PROMETHEUS_JAVAAGENT_VERSION}/jmx_prometheus_javaagent-${JMX_PROMETHEUS_JAVAAGENT_VERSION}.jar

RUN curl -O https://artifactory.vgt.vito.be/auxdata-public/openeo/dev/${OPENEO_ZIP} && \
    mkdir /opt/openeo /opt/tmp /batch_jobs /spark_tmp && \
    unzip -o /opt/${OPENEO_ZIP} -d /opt/openeo && \
    rm -rf /opt/${OPENEO_ZIP} && \
    rm -rf /opt/openeo/lib/python3.8/site-packages/tensorflow/* && \
    chown -R 18585:18585 /opt/openeo /opt/tmp /batch_jobs /spark_tmp

ENTRYPOINT [ "/opt/entrypoint.sh" ]

USER 18585
