FROM vito-docker-private.artifactory.vgt.vito.be/almalinux9.4

ARG TINI_VERSION=v0.19.0
ARG SPARK_PACKAGE
# Location where the spark package is installed to and to be symlinked to `/usr/local/spark`
ARG SPARK_INSTALL_PREFIX
ARG PYTHON_PACKAGE
ARG GEOTRELLIS_DEPENDENCIES_STATIC_JAR_URL


RUN sed -i '/^\[appstream\]/a module_hotfixes=1' /etc/yum.repos.d/alma_9.4.repo

COPY docker/AlmaLinux/vito_almalinux9.repo /etc/yum.repos.d/vito.repo

WORKDIR /opt/spark/work-dir

ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini

RUN dnf clean all && dnf install -y epel-release && \
    dnf --enablerepo=crb install -y ${SPARK_PACKAGE} \
    glibc-langpack-en \
    orfeo-toolbox-py311 \
    hdf5 \
    gdal-3.8.4 \
    gdal-devel-3.8.4 \
    gdal-libs-3.8.4 \
    gdal-python311-3.8.4 \
    gcc-c++ \
    unzip \
    java-21-openjdk-headless \
    krb5-workstation \
    krb5-libs \
    sssd-client \
    ipa-client \
    nss \
    boost-filesystem \
    boost-serialization \
    procps-ng \
    ${PYTHON_PACKAGE} \
    python3.11-pip \
    python3.11-Cython \
    fftw-libs-double \
    fftw-libs-single \
    tinyxml \
    udunits2 \
    R-core \
    libtiff-tools \
    blosc \
    compat-libgfortran-48 \
    openeo-vito-aux-data && \
    python3.11 -m pip install --upgrade --target /usr/lib64/python3.11/site-packages/ pip setuptools wheel && \
    python3.11 -m pip install --upgrade --target /usr/lib64/python3.11/site-packages/ 'rpy2==3.5.12' && \
    chmod +x /usr/bin/tini && \
    rm -r /root/.cache && \
    yum clean all && \
    rm -rf /var/cache/yum/*


RUN if [ -n "${SPARK_INSTALL_PREFIX}" ]; then ln -s ${SPARK_INSTALL_PREFIX} /usr/local/spark; fi

ENV SPARK_HOME /usr/local/spark
ENV JAVA_HOME /usr/lib/jvm/jre
ENV PYSPARK_PYTHON=python3.11
ENV PYTHONPLATLIBDIR=lib64
ENV HADOOP_HOME=/usr/hdp/current/hadoop-client
ENV HADOOP_CONF_DIR=/etc/hadoop/conf
ENV YARN_CONF_DIR=/etc/hadoop/conf
ENV ACCUMULO_CLIENT_CONF_PATH=client.conf
ENV OTB_HOME=/usr
ENV OTB_APPLICATION_PATH=/usr/lib/otb/applications

ADD --chmod=755 $GEOTRELLIS_DEPENDENCIES_STATIC_JAR_URL /opt/geotrellis-dependencies-static.jar
