{{- if not .Values.existingConfigMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openeo-aggregator.fullname" . }}
data:
  {{- with .Values.configMaps.conf }}
  conf.py: |
{{- tpl . . | nindent 4 }}
  {{- end }}
{{- end }}
