{{- if not .Values.existingConfigMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openeo-aggregator.fullname" . }}-config
data:
  {{- if .Values.configMaps.conf }}
  conf.py: |
{{- tpl .Values.configMaps.conf . | nindent 4 }}
  {{- end }}
{{- end }}
