apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openeo-aggregator.fullname" . }}
  labels:
    {{- include "openeo-aggregator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openeo-aggregator.selectorLabels" . | nindent 6 }}
      {{- with .Values.labels }}
        {{- toYaml . | nindent 6}}
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openeo-aggregator.selectorLabels" . | nindent 8 }}
      {{- with .Values.labels }}
        {{- toYaml . | nindent 8}}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openeo-aggregator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.envVars .Values.configMaps.conf }}
          env:
          {{- if .Values.envVars }}
          {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.configMaps.conf }}
            - name: OPENEO_BACKEND_CONFIG
              value: "/conf/openeofed.conf.py"
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /openeo/1.2
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /openeo/1.2
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.volumeMounts (not .Values.existingConfigMaps) }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if not .Values.existingConfigMaps }}
            - name: {{ include "openeo-aggregator.fullname" . }}-config
              mountPath: /conf
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.volumes (not .Values.existingConfigMaps) }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if not .Values.existingConfigMaps }}
        - configMap:
            name: openeofed
            items:
              - key: conf.py
                path: openeofed.conf.py
          name: {{ include "openeo-aggregator.fullname" . }}-config
        {{- end }}
      {{- end }}
